const PRODUCTS = [
  {id:1, name:'Smartphone Alto Desempenho', emoji:'📱', category:'smartphones',
   desc:'Performance premium, câmera 108MP, bateria 5000mAh e carregamento rápido 65W.',
   price:2499, platform:'Amazon', badge:'DESTAQUE', featured:true,
   specs:['Câmera 108MP','Bateria 5000mAh','Carregamento 65W','128GB armazenamento','Tela AMOLED 6.7"']},
  {id:2, name:'Fone Sem Fio ANC Pro', emoji:'🎧', category:'audio',
   desc:'Cancelamento de ruído ativo, 30h de bateria e som Hi-Res Audio.',
   price:399.90, platform:'Shopee', badge:'NOVO', featured:true,
   specs:['ANC ativo','30h de bateria','Hi-Res Audio','Bluetooth 5.3','Dobrável']},
  {id:3, name:'Smartwatch Fitness GPS', emoji:'⌚', category:'wearables',
   desc:'Monitoramento de saúde completo, GPS integrado e tela AMOLED sempre ativa.',
   price:599, platform:'AliExpress', badge:'', featured:true,
   specs:['GPS integrado','SpO2 e frequência cardíaca','Tela AMOLED','5 ATM à prova d\'água','7 dias de bateria']},
  {id:4, name:'Caixa de Som 360° IPX7', emoji:'🔊', category:'audio',
   desc:'Som 360°, à prova d\'água IPX7 e 20 horas de autonomia. Ideal para aventuras.',
   price:289.90, platform:'Mercado Livre', badge:'', featured:false,
   specs:['IPX7 à prova d\'água','20h de bateria','360° de som','Bluetooth 5.0','True Wireless Stereo']},
  {id:5, name:'Controle Sem Fio Gamer', emoji:'🎮', category:'gaming',
   desc:'Compatível com PC, PS e Android. Vibração dupla e gatilhos adaptáveis.',
   price:199.90, platform:'Amazon', badge:'OFERTA', featured:false,
   specs:['Vibração dupla','Gatilhos adaptáveis','Bateria recarregável','Bluetooth + 2.4GHz','Compatível PC/Android']},
  {id:6, name:'Notebook Ultrafino 15"', emoji:'💻', category:'notebooks',
   desc:'Intel Core i5 12ª geração, 16GB RAM, SSD 512GB. Desempenho para trabalho e estudo.',
   price:3299, platform:'Amazon', badge:'PREMIUM', featured:true,
   specs:['Intel Core i5 12ª gen','16GB RAM DDR5','SSD 512GB NVMe','Tela IPS 15.6" FHD','12h de bateria']},
  {id:7, name:'Webcam 4K Streaming', emoji:'📷', category:'acessorios',
   desc:'4K a 30fps, microfone integrado com cancelamento de ruído. Para home office e streams.',
   price:349, platform:'Shopee', badge:'', featured:false,
   specs:['Resolução 4K 30fps','Microfone dual ANC','Auto foco','USB-C','Field of view 90°']},
  {id:8, name:'SSD Externo 1TB', emoji:'💾', category:'acessorios',
   desc:'Transferência até 1050MB/s, compacto e resistente a impactos. USB 3.2 Gen2.',
   price:459, platform:'AliExpress', badge:'', featured:false,
   specs:['1TB de capacidade','1050MB/s leitura','USB 3.2 Gen2','Resistente a impactos','Peso 50g']},
  {id:9, name:'Teclado Mecânico RGB', emoji:'⌨️', category:'gaming',
   desc:'Switches Red lineares, RGB por tecla e design compacto TKL. Para gamers e criadores.',
   price:279, platform:'Mercado Livre', badge:'NOVO', featured:false,
   specs:['Switches Red lineares','RGB por tecla','Layout TKL 87 teclas','Anti-ghosting','USB-C destacável']},
  {id:10, name:'Monitor Curvo 27" 165Hz', emoji:'🖥️', category:'gaming',
   desc:'1800R de curvatura, 165Hz, 1ms e painel VA. Imersão total nos jogos.',
   price:1799, platform:'Amazon', badge:'DESTAQUE', featured:true,
   specs:['27" curvo 1800R','165Hz taxa de atualização','1ms tempo de resposta','Painel VA FHD','AMD FreeSync']},
  {id:11, name:'Earbuds TWS Premium', emoji:'🎵', category:'audio',
   desc:'Driver dinâmico 12mm, ANC híbrido e 36h de autonomia com estojo.',
   price:229.90, platform:'Shopee', badge:'', featured:false,
   specs:['ANC híbrido','36h total (6h + estojo)','Driver 12mm','IPX5','Modo transparência']},
  {id:12, name:'Roteador Wi-Fi 6 AX3000', emoji:'📡', category:'acessorios',
   desc:'Wi-Fi 6 3000Mbps, 4 antenas de alto ganho e cobertura até 300m².',
   price:489, platform:'AliExpress', badge:'', featured:false,
   specs:['Wi-Fi 6 AX3000','Cobertura 300m²','4 portas Gigabit','MU-MIMO','Controle via app']},
];

const CATEGORIES = [
  {id:'todos', label:'Todos'},
  {id:'smartphones', label:'Smartphones'},
  {id:'audio', label:'Áudio'},
  {id:'wearables', label:'Wearables'},
  {id:'gaming', label:'Gaming'},
  {id:'notebooks', label:'Notebooks'},
  {id:'acessorios', label:'Acessórios'},
];
